### ISSUE TITLE
Unable to add Datasource projects and Dataservice projects under Multi-module maven project 

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#755] opened 2020-03-10 09:14 UTC
**Description:**
Unable to add Datasource projects and Data service projects under Multi-module maven project 

**Affected Product Version:**
7.0.2 RC2

**OS, DB, other environment details and versions:**    
Windows 

**Steps to reproduce:**

1. Create a multi-module maven project. 
2. Create a Data source project. In the wizard, select created multi-module maven project above. 
3. When click finished, no project is created !!

**Comment by sajithaliyanage** [comment] 2020-03-10 11:40
We tested the above scenario in Mac, Windows and Linux platforms. but could not able to reproduce the issue. Hence, close this issue.

**Closed** 2020-03-10 11:40 UTC
Labels: DSS, Severity/Critical
