### ISSUE TITLE
Reduce space between elements in generated property panel

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#1092] opened 2020-06-14 09:55 UTC
**Description:**
$subject please as we have discussed in synup, better reduce spaces between textboxes and other elements for a compact view. It reduces scrolling as well.

**Comment by prabushi** [comment] 2020-06-15 04:36
Duplicate of https://github.com/wso2/devstudio-tooling-ei/issues/1082

**Closed by prabushi** 2020-06-15 04:36 UTC
Labels: Resolution/Duplicate, Type/Improvement
