### ISSUE TITLE
Solution Project - Carbon Application doing nothing

### ISSUE THREAD

**Issue by eapereira** [wso2/devstudio-tooling-ei#176] opened 2018-05-17 21:04 UTC
Hello folks, I just created a "Solution Project" and deployed that at wso2, I was following some tutorial. That project has a Rest API, some logs and a web service. All fine.

But after starting wso2 I tried to call my Carbon Application and nothing returned on browser and nothing at console log. Here are my xmls:

**HealthcareAPI**
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/healthcare" name="HealthcareAPI" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET" uri-template=" /querydoctor/{category}">
        <inSequence>
            <log category="DEBUG" description="RequestLog">
                <property name="message" value="Welcome to HealthcareService"/>
            </log>
            <send>
                <endpoint key="QueryDoctorEP"/>
            </send>
        </inSequence>
        <outSequence>
            <log category="DEBUG" description="ResponseLog"/>
            <send/>
        </outSequence>
        <faultSequence>
            <log category="DEBUG" description="FaultLog"/>
        </faultSequence>
    </resource>
</api>
```

**QueryDoctorEP**
```
<?xml version="1.0" encoding="UTF-8"?>
<endpoint name="QueryDoctorEP" xmlns="http://ws.apache.org/ns/synapse">
    <http method="get" uri-template="http://wso2training-restsamples.wso2apps.com/healthcare/{uri.var.category}"/>
</endpoint>

```

**Comment by sohaniwso2** [comment] 2018-06-01 12:39
Hi,

Could you please confirm whether you included the created artifacts (Inside ESB Project) to the CAPP project before deploying it to the server? 

Could you please refer https://docs.wso2.com/display/ADMIN44x/Working+with+Composite+Applications for more information n packaging artifacts and deploying

**Comment by eapereira** [comment] 2018-06-01 23:49
Sorry there are some errors with this ESB Solution Project, first there is no payload-factory to the endpoint and also there is no work with the response. I already fixed:

**Comment by sohaniwso2** [comment] 2018-06-02 06:50
Hope the problem is solved now hence I'm closing the issue. Please reopen if you face any issues

Thanks,
Sohani

**Closed by sohaniwso2** 2018-06-02 06:50 UTC
